package soa.db.palm.entity;
// Generated Apr 18, 2019 10:21:13 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Bugreport generated by hbm2java
 */
public class Bugreport  implements java.io.Serializable {


     private Integer idBug;
     private Farmer farmer;
     private Date date;
     private Integer insecticide;
     private Date datereport;
     private Set imagebugreports = new HashSet(0);
     private Set palmtobugreports = new HashSet(0);

    public Bugreport() {
    }

    public Bugreport(int idBug, Farmer farmer) {
        this.idBug = idBug;
        this.farmer = farmer;
    }	
      public Bugreport(Farmer farmer) {
        this.farmer = farmer;
    }
    public Bugreport(Farmer farmer, Date datereport) {
        this.farmer = farmer;
        this.datereport = datereport;
    }
    public Bugreport(Farmer farmer, Date date, Integer insecticide, Date datereport, Set imagebugreports, Set palmtobugreports) {
       this.farmer = farmer;
       this.date = date;
       this.insecticide = insecticide;
       this.datereport = datereport;
       this.imagebugreports = imagebugreports;
       this.palmtobugreports = palmtobugreports;
    }
   
    public Integer getIdBug() {
        return this.idBug;
    }
    
    public void setIdBug(Integer idBug) {
        this.idBug = idBug;
    }
    public Farmer getFarmer() {
        return this.farmer;
    }
    
    public void setFarmer(Farmer farmer) {
        this.farmer = farmer;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Integer getInsecticide() {
        return this.insecticide;
    }
    
    public void setInsecticide(Integer insecticide) {
        this.insecticide = insecticide;
    }
    public Date getDatereport() {
        return this.datereport;
    }
    
    public void setDatereport(Date datereport) {
        this.datereport = datereport;
    }
    public Set getImagebugreports() {
        return this.imagebugreports;
    }
    
    public void setImagebugreports(Set imagebugreports) {
        this.imagebugreports = imagebugreports;
    }
    public Set getPalmtobugreports() {
        return this.palmtobugreports;
    }
    
    public void setPalmtobugreports(Set palmtobugreports) {
        this.palmtobugreports = palmtobugreports;
    }




}


