package soa.db.palm.entity;
// Generated Apr 18, 2019 10:21:13 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Carwaterreport generated by hbm2java
 */
public class Carwaterreport  implements java.io.Serializable {


     private Integer idCarWaterReport;
     private Farmer farmer;
     private Date date;
     private Integer number;
     private Date datereport;
     private Set palmtocarwaterreports = new HashSet(0);

    public Carwaterreport() {
    }
    public Carwaterreport(int idCarWaterReport, Farmer farmer) {
        this.idCarWaterReport = idCarWaterReport;
        this.farmer = farmer;
    }	
      public Carwaterreport(Farmer farmer) {
        this.farmer = farmer;
    }
	
    public Carwaterreport(Farmer farmer, Date datereport) {
        this.farmer = farmer;
        this.datereport = datereport;
    }
    public Carwaterreport(Farmer farmer, Date date, Integer number, Date datereport, Set palmtocarwaterreports) {
       this.farmer = farmer;
       this.date = date;
       this.number = number;
       this.datereport = datereport;
       this.palmtocarwaterreports = palmtocarwaterreports;
    }
   
    public Integer getIdCarWaterReport() {
        return this.idCarWaterReport;
    }
    
    public void setIdCarWaterReport(Integer idCarWaterReport) {
        this.idCarWaterReport = idCarWaterReport;
    }
    public Farmer getFarmer() {
        return this.farmer;
    }
    
    public void setFarmer(Farmer farmer) {
        this.farmer = farmer;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Integer getNumber() {
        return this.number;
    }
    
    public void setNumber(Integer number) {
        this.number = number;
    }
    public Date getDatereport() {
        return this.datereport;
    }
    
    public void setDatereport(Date datereport) {
        this.datereport = datereport;
    }
    public Set getPalmtocarwaterreports() {
        return this.palmtocarwaterreports;
    }
    
    public void setPalmtocarwaterreports(Set palmtocarwaterreports) {
        this.palmtocarwaterreports = palmtocarwaterreports;
    }




}


