package soa.db.palm.entity;
// Generated Apr 18, 2019 10:21:13 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cutleafreport generated by hbm2java
 */
public class Cutleafreport  implements java.io.Serializable {


     private Integer idCutLeafReport;
     private Farmer farmer;
     private Date date;
     private Date datereport;
     private Set palmtocutleafreports = new HashSet(0);

    public Cutleafreport() {
    }

    public Cutleafreport(int idCutLeafReport, Farmer farmer) {
        this.idCutLeafReport = idCutLeafReport;
        this.farmer = farmer;
    }	
      public Cutleafreport(Farmer farmer) {
        this.farmer = farmer;
    }
    public Cutleafreport(Farmer farmer, Date datereport) {
        this.farmer = farmer;
        this.datereport = datereport;
    }
    public Cutleafreport(Farmer farmer, Date date, Date datereport, Set palmtocutleafreports) {
       this.farmer = farmer;
       this.date = date;
       this.datereport = datereport;
       this.palmtocutleafreports = palmtocutleafreports;
    }
   
    public Integer getIdCutLeafReport() {
        return this.idCutLeafReport;
    }
    
    public void setIdCutLeafReport(Integer idCutLeafReport) {
        this.idCutLeafReport = idCutLeafReport;
    }
    public Farmer getFarmer() {
        return this.farmer;
    }
    
    public void setFarmer(Farmer farmer) {
        this.farmer = farmer;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getDatereport() {
        return this.datereport;
    }
    
    public void setDatereport(Date datereport) {
        this.datereport = datereport;
    }
    public Set getPalmtocutleafreports() {
        return this.palmtocutleafreports;
    }
    
    public void setPalmtocutleafreports(Set palmtocutleafreports) {
        this.palmtocutleafreports = palmtocutleafreports;
    }




}


