package soa.db.palm.entity;
// Generated Apr 18, 2019 10:21:13 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {


     private Integer idEvent;
     private Farmer farmer;
     private Date date;
     private String name;
     private String detail;

    public Event() {
    }
    
    public Event(int idEvent, Farmer farmer) {
        this.idEvent = idEvent;
        this.farmer = farmer;
    }	
   
	
    public Event(Farmer farmer) {
        this.farmer = farmer;
    }
    public Event(Farmer farmer, Date date, String name, String detail) {
       this.farmer = farmer;
       this.date = date;
       this.name = name;
       this.detail = detail;
    }
   
    public Integer getIdEvent() {
        return this.idEvent;
    }
    
    public void setIdEvent(Integer idEvent) {
        this.idEvent = idEvent;
    }
    public Farmer getFarmer() {
        return this.farmer;
    }
    
    public void setFarmer(Farmer farmer) {
        this.farmer = farmer;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }




}


