package soa.db.palm.entity;
// Generated Apr 18, 2019 10:21:13 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Farmer generated by hbm2java
 */
public class Farmer  implements java.io.Serializable {


     private Integer idFarmer;
     private String username;
     private String password;
     private String fname;
     private String lname;
     private Long idCard;
     private String address;
     private String city;
     private String phoneNumber;
     private String image;
     private String url;
     private Integer status;
     private Set addressplams = new HashSet(0);
     private Set fertilizerreports = new HashSet(0);
     private Set cutleafreports = new HashSet(0);
     private Set carwaterreports = new HashSet(0);
     private Set rainreports = new HashSet(0);
     private Set waterreports = new HashSet(0);
     private Set bugreports = new HashSet(0);
     private Set weedreports = new HashSet(0);
     private Set events = new HashSet(0);
     private Set harvestreports = new HashSet(0);
     private Set plantdiseaseses = new HashSet(0);

    public Farmer() {
    }
   public Farmer(int idFarmer) {
        this.idFarmer = idFarmer;
    }
	
    public Farmer(String url) {
        this.url = url;
    }
    public Farmer(String username, String password, String fname, String lname, Long idCard, String address, String city, String phoneNumber, String image, String url, Integer status, Set addressplams, Set fertilizerreports, Set cutleafreports, Set carwaterreports, Set rainreports, Set waterreports, Set bugreports, Set weedreports, Set events, Set harvestreports, Set plantdiseaseses) {
       this.username = username;
       this.password = password;
       this.fname = fname;
       this.lname = lname;
       this.idCard = idCard;
       this.address = address;
       this.city = city;
       this.phoneNumber = phoneNumber;
       this.image = image;
       this.url = url;
       this.status = status;
       this.addressplams = addressplams;
       this.fertilizerreports = fertilizerreports;
       this.cutleafreports = cutleafreports;
       this.carwaterreports = carwaterreports;
       this.rainreports = rainreports;
       this.waterreports = waterreports;
       this.bugreports = bugreports;
       this.weedreports = weedreports;
       this.events = events;
       this.harvestreports = harvestreports;
       this.plantdiseaseses = plantdiseaseses;
    }
   
    public Integer getIdFarmer() {
        return this.idFarmer;
    }
    
    public void setIdFarmer(Integer idFarmer) {
        this.idFarmer = idFarmer;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public Long getIdCard() {
        return this.idCard;
    }
    
    public void setIdCard(Long idCard) {
        this.idCard = idCard;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Set getAddressplams() {
        return this.addressplams;
    }
    
    public void setAddressplams(Set addressplams) {
        this.addressplams = addressplams;
    }
    public Set getFertilizerreports() {
        return this.fertilizerreports;
    }
    
    public void setFertilizerreports(Set fertilizerreports) {
        this.fertilizerreports = fertilizerreports;
    }
    public Set getCutleafreports() {
        return this.cutleafreports;
    }
    
    public void setCutleafreports(Set cutleafreports) {
        this.cutleafreports = cutleafreports;
    }
    public Set getCarwaterreports() {
        return this.carwaterreports;
    }
    
    public void setCarwaterreports(Set carwaterreports) {
        this.carwaterreports = carwaterreports;
    }
    public Set getRainreports() {
        return this.rainreports;
    }
    
    public void setRainreports(Set rainreports) {
        this.rainreports = rainreports;
    }
    public Set getWaterreports() {
        return this.waterreports;
    }
    
    public void setWaterreports(Set waterreports) {
        this.waterreports = waterreports;
    }
    public Set getBugreports() {
        return this.bugreports;
    }
    
    public void setBugreports(Set bugreports) {
        this.bugreports = bugreports;
    }
    public Set getWeedreports() {
        return this.weedreports;
    }
    
    public void setWeedreports(Set weedreports) {
        this.weedreports = weedreports;
    }
    public Set getEvents() {
        return this.events;
    }
    
    public void setEvents(Set events) {
        this.events = events;
    }
    public Set getHarvestreports() {
        return this.harvestreports;
    }
    
    public void setHarvestreports(Set harvestreports) {
        this.harvestreports = harvestreports;
    }
    public Set getPlantdiseaseses() {
        return this.plantdiseaseses;
    }
    
    public void setPlantdiseaseses(Set plantdiseaseses) {
        this.plantdiseaseses = plantdiseaseses;
    }




}


