package soa.db.palm.entity;
// Generated Apr 18, 2019 10:21:13 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Fertilizerreport generated by hbm2java
 */
public class Fertilizerreport  implements java.io.Serializable {


     private Integer idFertilizerReport;
     private Farmer farmer;
     private String fertilizer;
     private Date date;
     private Integer volume;
     private Date datereport;
     private Set imagefertilizerreports = new HashSet(0);
     private Set palmtofertilizerreports = new HashSet(0);

    public Fertilizerreport() {
    }
    public Fertilizerreport(int idFertilizerReport, Farmer farmer) {
        this.idFertilizerReport = idFertilizerReport;
        this.farmer = farmer;
    }
     public Fertilizerreport(Farmer farmer) {
        this.farmer = farmer;
    }
    public Fertilizerreport(Farmer farmer, Date datereport) {
        this.farmer = farmer;
        this.datereport = datereport;
    }
    public Fertilizerreport(Farmer farmer, String fertilizer, Date date, Integer volume, Date datereport, Set imagefertilizerreports, Set palmtofertilizerreports) {
       this.farmer = farmer;
       this.fertilizer = fertilizer;
       this.date = date;
       this.volume = volume;
       this.datereport = datereport;
       this.imagefertilizerreports = imagefertilizerreports;
       this.palmtofertilizerreports = palmtofertilizerreports;
    }
   
    public Integer getIdFertilizerReport() {
        return this.idFertilizerReport;
    }
    
    public void setIdFertilizerReport(Integer idFertilizerReport) {
        this.idFertilizerReport = idFertilizerReport;
    }
    public Farmer getFarmer() {
        return this.farmer;
    }
    
    public void setFarmer(Farmer farmer) {
        this.farmer = farmer;
    }
    public String getFertilizer() {
        return this.fertilizer;
    }
    
    public void setFertilizer(String fertilizer) {
        this.fertilizer = fertilizer;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Integer getVolume() {
        return this.volume;
    }
    
    public void setVolume(Integer volume) {
        this.volume = volume;
    }
    public Date getDatereport() {
        return this.datereport;
    }
    
    public void setDatereport(Date datereport) {
        this.datereport = datereport;
    }
    public Set getImagefertilizerreports() {
        return this.imagefertilizerreports;
    }
    
    public void setImagefertilizerreports(Set imagefertilizerreports) {
        this.imagefertilizerreports = imagefertilizerreports;
    }
    public Set getPalmtofertilizerreports() {
        return this.palmtofertilizerreports;
    }
    
    public void setPalmtofertilizerreports(Set palmtofertilizerreports) {
        this.palmtofertilizerreports = palmtofertilizerreports;
    }




}


