package soa.db.palm.entity;
// Generated Apr 18, 2019 10:21:13 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Harvestreport generated by hbm2java
 */
public class Harvestreport  implements java.io.Serializable {


     private Integer idHarvestReport;
     private Farmer farmer;
     private Date date;
     private Integer number;
     private Integer numToMoney;
     private Integer money;
     private Date datereport;
     private Set palmtoharvestreports = new HashSet(0);
     private Set imageharvestreports = new HashSet(0);

    public Harvestreport() {
    }

    public Harvestreport(int idHarvestReport, Farmer farmer) {
        this.idHarvestReport = idHarvestReport;
        this.farmer = farmer;
    }	
    public Harvestreport(Farmer farmer) {
        this.farmer = farmer;
    }
	
    public Harvestreport(Farmer farmer, Date datereport) {
        this.farmer = farmer;
        this.datereport = datereport;
    }
    public Harvestreport(Farmer farmer, Date date, Integer number, Integer numToMoney, Integer money, Date datereport, Set palmtoharvestreports, Set imageharvestreports) {
       this.farmer = farmer;
       this.date = date;
       this.number = number;
       this.numToMoney = numToMoney;
       this.money = money;
       this.datereport = datereport;
       this.palmtoharvestreports = palmtoharvestreports;
       this.imageharvestreports = imageharvestreports;
    }
   
    public Integer getIdHarvestReport() {
        return this.idHarvestReport;
    }
    
    public void setIdHarvestReport(Integer idHarvestReport) {
        this.idHarvestReport = idHarvestReport;
    }
    public Farmer getFarmer() {
        return this.farmer;
    }
    
    public void setFarmer(Farmer farmer) {
        this.farmer = farmer;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Integer getNumber() {
        return this.number;
    }
    
    public void setNumber(Integer number) {
        this.number = number;
    }
    public Integer getNumToMoney() {
        return this.numToMoney;
    }
    
    public void setNumToMoney(Integer numToMoney) {
        this.numToMoney = numToMoney;
    }
    public Integer getMoney() {
        return this.money;
    }
    
    public void setMoney(Integer money) {
        this.money = money;
    }
    public Date getDatereport() {
        return this.datereport;
    }
    
    public void setDatereport(Date datereport) {
        this.datereport = datereport;
    }
    public Set getPalmtoharvestreports() {
        return this.palmtoharvestreports;
    }
    
    public void setPalmtoharvestreports(Set palmtoharvestreports) {
        this.palmtoharvestreports = palmtoharvestreports;
    }
    public Set getImageharvestreports() {
        return this.imageharvestreports;
    }
    
    public void setImageharvestreports(Set imageharvestreports) {
        this.imageharvestreports = imageharvestreports;
    }




}


