package soa.db.palm.entity;
// Generated Apr 18, 2019 10:21:13 PM by Hibernate Tools 4.3.1



/**
 * Imagefertilizerreport generated by hbm2java
 */
public class Imagefertilizerreport  implements java.io.Serializable {


     private Integer idImageFertilizer;
     private Fertilizerreport fertilizerreport;
     private String image;
     private String url;

    public Imagefertilizerreport() {
    }

	
    public Imagefertilizerreport(Fertilizerreport fertilizerreport, String url) {
        this.fertilizerreport = fertilizerreport;
        this.url = url;
    }
    public Imagefertilizerreport(Fertilizerreport fertilizerreport, String image, String url) {
       this.fertilizerreport = fertilizerreport;
       this.image = image;
       this.url = url;
    }
   
    public Integer getIdImageFertilizer() {
        return this.idImageFertilizer;
    }
    
    public void setIdImageFertilizer(Integer idImageFertilizer) {
        this.idImageFertilizer = idImageFertilizer;
    }
    public Fertilizerreport getFertilizerreport() {
        return this.fertilizerreport;
    }
    
    public void setFertilizerreport(Fertilizerreport fertilizerreport) {
        this.fertilizerreport = fertilizerreport;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


