package soa.db.palm.entity;
// Generated Apr 18, 2019 10:21:13 PM by Hibernate Tools 4.3.1



/**
 * Imageharvestreport generated by hbm2java
 */
public class Imageharvestreport  implements java.io.Serializable {


     private Integer idImageHarvest;
     private Harvestreport harvestreport;
     private String url;
     private String image;

    public Imageharvestreport() {
    }

	
    public Imageharvestreport(Harvestreport harvestreport, String url) {
        this.harvestreport = harvestreport;
        this.url = url;
    }
    public Imageharvestreport(Harvestreport harvestreport, String url, String image) {
       this.harvestreport = harvestreport;
       this.url = url;
       this.image = image;
    }
   
    public Integer getIdImageHarvest() {
        return this.idImageHarvest;
    }
    
    public void setIdImageHarvest(Integer idImageHarvest) {
        this.idImageHarvest = idImageHarvest;
    }
    public Harvestreport getHarvestreport() {
        return this.harvestreport;
    }
    
    public void setHarvestreport(Harvestreport harvestreport) {
        this.harvestreport = harvestreport;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }




}


