package soa.db.palm.entity;
// Generated Apr 18, 2019 10:21:13 PM by Hibernate Tools 4.3.1



/**
 * Makepalm generated by hbm2java
 */
public class Makepalm  implements java.io.Serializable {


     private Integer idMakePalm;
     private Addressplam addressplam;
     private String lat;
     private String long_;

    public Makepalm() {
    }

	
    public Makepalm(Addressplam addressplam) {
        this.addressplam = addressplam;
    }
    public Makepalm(Addressplam addressplam, String lat, String long_) {
       this.addressplam = addressplam;
       this.lat = lat;
       this.long_ = long_;
    }
   
    public Integer getIdMakePalm() {
        return this.idMakePalm;
    }
    
    public void setIdMakePalm(Integer idMakePalm) {
        this.idMakePalm = idMakePalm;
    }
    public Addressplam getAddressplam() {
        return this.addressplam;
    }
    
    public void setAddressplam(Addressplam addressplam) {
        this.addressplam = addressplam;
    }
    public String getLat() {
        return this.lat;
    }
    
    public void setLat(String lat) {
        this.lat = lat;
    }
    public String getLong_() {
        return this.long_;
    }
    
    public void setLong_(String long_) {
        this.long_ = long_;
    }




}


