package soa.db.palm.entity;
// Generated Apr 18, 2019 10:21:13 PM by Hibernate Tools 4.3.1



/**
 * Palmtobugreport generated by hbm2java
 */
public class Palmtobugreport  implements java.io.Serializable {


     private Integer idPalmToBug;
     private Addressplam addressplam;
     private Bugreport bugreport;

    public Palmtobugreport() {
    }

    public Palmtobugreport(Addressplam addressplam, Bugreport bugreport) {
       this.addressplam = addressplam;
       this.bugreport = bugreport;
    }
   
    public Integer getIdPalmToBug() {
        return this.idPalmToBug;
    }
    
    public void setIdPalmToBug(Integer idPalmToBug) {
        this.idPalmToBug = idPalmToBug;
    }
    public Addressplam getAddressplam() {
        return this.addressplam;
    }
    
    public void setAddressplam(Addressplam addressplam) {
        this.addressplam = addressplam;
    }
    public Bugreport getBugreport() {
        return this.bugreport;
    }
    
    public void setBugreport(Bugreport bugreport) {
        this.bugreport = bugreport;
    }




}


