package soa.db.palm.entity;
// Generated Apr 18, 2019 10:21:13 PM by Hibernate Tools 4.3.1



/**
 * Palmtoplantdiseases generated by hbm2java
 */
public class Palmtoplantdiseases  implements java.io.Serializable {


     private Integer idPalmToPlantDiseases;
     private Addressplam addressplam;
     private Plantdiseases plantdiseases;

    public Palmtoplantdiseases() {
    }

    public Palmtoplantdiseases(Addressplam addressplam, Plantdiseases plantdiseases) {
       this.addressplam = addressplam;
       this.plantdiseases = plantdiseases;
    }
   
    public Integer getIdPalmToPlantDiseases() {
        return this.idPalmToPlantDiseases;
    }
    
    public void setIdPalmToPlantDiseases(Integer idPalmToPlantDiseases) {
        this.idPalmToPlantDiseases = idPalmToPlantDiseases;
    }
    public Addressplam getAddressplam() {
        return this.addressplam;
    }
    
    public void setAddressplam(Addressplam addressplam) {
        this.addressplam = addressplam;
    }
    public Plantdiseases getPlantdiseases() {
        return this.plantdiseases;
    }
    
    public void setPlantdiseases(Plantdiseases plantdiseases) {
        this.plantdiseases = plantdiseases;
    }




}


