package soa.db.palm.entity;
// Generated Apr 18, 2019 10:21:13 PM by Hibernate Tools 4.3.1



/**
 * Palmtocarwaterreport generated by hbm2java
 */
public class Palmtocarwaterreport  implements java.io.Serializable {


     private Integer idPalmToCarWater;
     private Addressplam addressplam;
     private Carwaterreport carwaterreport;

    public Palmtocarwaterreport() {
    }

    public Palmtocarwaterreport(Addressplam addressplam, Carwaterreport carwaterreport) {
       this.addressplam = addressplam;
       this.carwaterreport = carwaterreport;
    }
   
    public Integer getIdPalmToCarWater() {
        return this.idPalmToCarWater;
    }
    
    public void setIdPalmToCarWater(Integer idPalmToCarWater) {
        this.idPalmToCarWater = idPalmToCarWater;
    }
    public Addressplam getAddressplam() {
        return this.addressplam;
    }
    
    public void setAddressplam(Addressplam addressplam) {
        this.addressplam = addressplam;
    }
    public Carwaterreport getCarwaterreport() {
        return this.carwaterreport;
    }
    
    public void setCarwaterreport(Carwaterreport carwaterreport) {
        this.carwaterreport = carwaterreport;
    }




}


