package soa.db.palm.entity;
// Generated Apr 18, 2019 10:21:13 PM by Hibernate Tools 4.3.1



/**
 * Palmtoharvestreport generated by hbm2java
 */
public class Palmtoharvestreport  implements java.io.Serializable {


     private Integer idPalmToHarvest;
     private Addressplam addressplam;
     private Harvestreport harvestreport;

    public Palmtoharvestreport() {
    }

    public Palmtoharvestreport(Addressplam addressplam, Harvestreport harvestreport) {
       this.addressplam = addressplam;
       this.harvestreport = harvestreport;
    }
   
    public Integer getIdPalmToHarvest() {
        return this.idPalmToHarvest;
    }
    
    public void setIdPalmToHarvest(Integer idPalmToHarvest) {
        this.idPalmToHarvest = idPalmToHarvest;
    }
    public Addressplam getAddressplam() {
        return this.addressplam;
    }
    
    public void setAddressplam(Addressplam addressplam) {
        this.addressplam = addressplam;
    }
    public Harvestreport getHarvestreport() {
        return this.harvestreport;
    }
    
    public void setHarvestreport(Harvestreport harvestreport) {
        this.harvestreport = harvestreport;
    }




}


