package soa.db.palm.entity;
// Generated Apr 18, 2019 10:21:13 PM by Hibernate Tools 4.3.1



/**
 * Palmtoweedreport generated by hbm2java
 */
public class Palmtoweedreport  implements java.io.Serializable {


     private Integer idPalmToWeedReport;
     private Addressplam addressplam;
     private Weedreport weedreport;

    public Palmtoweedreport() {
    }

    public Palmtoweedreport(Addressplam addressplam, Weedreport weedreport) {
       this.addressplam = addressplam;
       this.weedreport = weedreport;
    }
   
    public Integer getIdPalmToWeedReport() {
        return this.idPalmToWeedReport;
    }
    
    public void setIdPalmToWeedReport(Integer idPalmToWeedReport) {
        this.idPalmToWeedReport = idPalmToWeedReport;
    }
    public Addressplam getAddressplam() {
        return this.addressplam;
    }
    
    public void setAddressplam(Addressplam addressplam) {
        this.addressplam = addressplam;
    }
    public Weedreport getWeedreport() {
        return this.weedreport;
    }
    
    public void setWeedreport(Weedreport weedreport) {
        this.weedreport = weedreport;
    }




}


