package soa.db.palm.entity;
// Generated Apr 18, 2019 10:21:13 PM by Hibernate Tools 4.3.1



/**
 * Palmtowaterreport generated by hbm2java
 */
public class Palmtowaterreport  implements java.io.Serializable {


     private int idPalmToWater;
     private Addressplam addressplam;
     private Waterreport waterreport;

    public Palmtowaterreport() {
    }

    public Palmtowaterreport(int idPalmToWater, Addressplam addressplam, Waterreport waterreport) {
       this.idPalmToWater = idPalmToWater;
       this.addressplam = addressplam;
       this.waterreport = waterreport;
    }
   
    public int getIdPalmToWater() {
        return this.idPalmToWater;
    }
    
    public void setIdPalmToWater(int idPalmToWater) {
        this.idPalmToWater = idPalmToWater;
    }
    public Addressplam getAddressplam() {
        return this.addressplam;
    }
    
    public void setAddressplam(Addressplam addressplam) {
        this.addressplam = addressplam;
    }
    public Waterreport getWaterreport() {
        return this.waterreport;
    }
    
    public void setWaterreport(Waterreport waterreport) {
        this.waterreport = waterreport;
    }




}


