package soa.db.palm.entity;
// Generated Apr 18, 2019 10:21:13 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Plantdiseases generated by hbm2java
 */
public class Plantdiseases  implements java.io.Serializable {


     private Integer idPlantDiseases;
     private Farmer farmer;
     private Date date;
     private String symptom;
     private String diseases;
     private Date datereport;
     private Set palmtoplantdiseaseses = new HashSet(0);
     private Set imageplantdiseaseses = new HashSet(0);

    public Plantdiseases() {
    }

    public Plantdiseases(int idPlantDiseases, Farmer farmer) {
        this.idPlantDiseases = idPlantDiseases;
        this.farmer = farmer;
    }	
    public Plantdiseases(Farmer farmer) {
        this.farmer = farmer;
    }
    public Plantdiseases(Farmer farmer, Date datereport) {
        this.farmer = farmer;
        this.datereport = datereport;
    }
    public Plantdiseases(Farmer farmer, Date date, String symptom, String diseases, Date datereport, Set palmtoplantdiseaseses, Set imageplantdiseaseses) {
       this.farmer = farmer;
       this.date = date;
       this.symptom = symptom;
       this.diseases = diseases;
       this.datereport = datereport;
       this.palmtoplantdiseaseses = palmtoplantdiseaseses;
       this.imageplantdiseaseses = imageplantdiseaseses;
    }
   
    public Integer getIdPlantDiseases() {
        return this.idPlantDiseases;
    }
    
    public void setIdPlantDiseases(Integer idPlantDiseases) {
        this.idPlantDiseases = idPlantDiseases;
    }
    public Farmer getFarmer() {
        return this.farmer;
    }
    
    public void setFarmer(Farmer farmer) {
        this.farmer = farmer;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getSymptom() {
        return this.symptom;
    }
    
    public void setSymptom(String symptom) {
        this.symptom = symptom;
    }
    public String getDiseases() {
        return this.diseases;
    }
    
    public void setDiseases(String diseases) {
        this.diseases = diseases;
    }
    public Date getDatereport() {
        return this.datereport;
    }
    
    public void setDatereport(Date datereport) {
        this.datereport = datereport;
    }
    public Set getPalmtoplantdiseaseses() {
        return this.palmtoplantdiseaseses;
    }
    
    public void setPalmtoplantdiseaseses(Set palmtoplantdiseaseses) {
        this.palmtoplantdiseaseses = palmtoplantdiseaseses;
    }
    public Set getImageplantdiseaseses() {
        return this.imageplantdiseaseses;
    }
    
    public void setImageplantdiseaseses(Set imageplantdiseaseses) {
        this.imageplantdiseaseses = imageplantdiseaseses;
    }




}


