package soa.db.palm.entity;
// Generated Apr 18, 2019 10:21:13 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Waterreport generated by hbm2java
 */
public class Waterreport  implements java.io.Serializable {


     private Integer idWaterReport;
     private Farmer farmer;
     private Date date;
     private Date datereport;
     private Set palmtowaterreports = new HashSet(0);

    public Waterreport() {
    }
     public Waterreport(int idWaterReport, Farmer farmer) {
        this.idWaterReport = idWaterReport;
        this.farmer = farmer;
    }	
    public Waterreport(Farmer farmer) {
        this.farmer = farmer;
    }
	
    public Waterreport(Farmer farmer, Date datereport) {
        this.farmer = farmer;
        this.datereport = datereport;
    }
    public Waterreport(Farmer farmer, Date date, Date datereport, Set palmtowaterreports) {
       this.farmer = farmer;
       this.date = date;
       this.datereport = datereport;
       this.palmtowaterreports = palmtowaterreports;
    }
   
    public Integer getIdWaterReport() {
        return this.idWaterReport;
    }
    
    public void setIdWaterReport(Integer idWaterReport) {
        this.idWaterReport = idWaterReport;
    }
    public Farmer getFarmer() {
        return this.farmer;
    }
    
    public void setFarmer(Farmer farmer) {
        this.farmer = farmer;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getDatereport() {
        return this.datereport;
    }
    
    public void setDatereport(Date datereport) {
        this.datereport = datereport;
    }
    public Set getPalmtowaterreports() {
        return this.palmtowaterreports;
    }
    
    public void setPalmtowaterreports(Set palmtowaterreports) {
        this.palmtowaterreports = palmtowaterreports;
    }




}


